"""Regression tests built from real captured trading-partner NAESB Internet
ET transmissions (`samples/request-ssc-*.txt`) -- the first real-world
traffic this gateway has been checked against, as opposed to synthetic
payloads generated by its own build_multipart_body()/wrap_pgp_encrypted().
These confirm the parsing layer actually tolerates the real-world quirks
these captures share: an inner multipart/encrypted boundary parameter that
itself starts with "--", no content-transfer-encoding header on the
octet-stream part, an ASCII-armored (not armor-less binary) OpenPGP
message, and an outer field order with input-data last rather than where
build_multipart_body() would place it.
"""

import re
from pathlib import Path

import pytest
from fastapi import FastAPI, Request
from fastapi.testclient import TestClient

from app.envelope.multipart_codec import parse_multipart_form

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "samples"

SAMPLE_FILENAMES = [
    "request-ssc-1.txt",
    "request-ssc-2.txt",
    "request-ssc-3.txt",
    "request-ssc-4.txt",
]

SAMPLE_REFNUMS = {
    "request-ssc-1.txt": "17839603431407195831",
    "request-ssc-2.txt": "17839604692365789297",
    "request-ssc-3.txt": "17839678205184831959",
    "request-ssc-4.txt": "17839693150211649056",
}


def _load_sample(filename: str) -> tuple[bytes, str]:
    """Read a captured request-line+headers+multipart-body transcript and
    reconstruct it as an HTTP body suitable for Starlette's multipart
    parser. The files on disk use bare LF line endings (confirmed: an
    artifact of however they were captured/saved -- the stated
    Content-Length header matches a CRLF-terminated byte count, not the
    on-disk LF one). Real HTTP/MIME framing requires CRLF, and
    python-multipart's parser enforces it strictly, so we normalize line
    endings here while preserving every real field value, boundary token,
    and structural quirk from the actual capture untouched."""
    raw = (SAMPLES_DIR / filename).read_bytes().replace(b"\n", b"\r\n")
    head, _, body = raw.partition(b"\r\n\r\n")
    content_type = None
    for line in head.split(b"\r\n")[1:]:
        if line.lower().startswith(b"content-type:"):
            content_type = line.split(b":", 1)[1].strip().decode()
    assert content_type is not None, f"{filename}: no content-type header found"
    return body, content_type


def _build_parse_app() -> FastAPI:
    app = FastAPI()

    @app.post("/parse")
    async def parse(request: Request):
        form = await request.form()
        fields, ciphertext = await parse_multipart_form(form)
        return {
            "from_id": fields.from_id,
            "to_id": fields.to_id,
            "version": fields.version,
            "refnum": fields.refnum,
            "refnum_orig": fields.refnum_orig,
            "transaction_set": fields.transaction_set,
            "receipt_security_selection": fields.receipt_security_selection,
            "ciphertext_hex": ciphertext.hex(),
        }

    return app


@pytest.mark.parametrize("filename", SAMPLE_FILENAMES)
def test_real_sample_parses_with_expected_fields(filename):
    body, content_type = _load_sample(filename)
    client = TestClient(_build_parse_app())

    response = client.post("/parse", content=body, headers={"content-type": content_type})

    assert response.status_code == 200
    data = response.json()
    assert data["from_id"] == "007906233"
    assert data["to_id"] == "080948376"
    assert data["version"] == "3.0"
    assert data["refnum"] == SAMPLE_REFNUMS[filename]
    assert data["refnum_orig"] == SAMPLE_REFNUMS[filename]
    assert data["transaction_set"] is None
    assert "sha1" in data["receipt_security_selection"]

    # unwrap_pgp_encrypted() must recover the exact armored OpenPGP message
    # bytes, untouched, despite the boundary/CTE/armor quirks below.
    ciphertext = bytes.fromhex(data["ciphertext_hex"])
    assert ciphertext.startswith(b"-----BEGIN PGP MESSAGE-----")
    assert ciphertext.endswith(b"-----END PGP MESSAGE-----")


@pytest.mark.parametrize("filename", SAMPLE_FILENAMES)
def test_real_sample_input_data_boundary_has_embedded_dashes(filename):
    """Every one of these real captures uses an inner multipart/encrypted
    boundary parameter that itself starts with "--"
    (e.g. boundary=--boundary2--POuv...), producing a
    "----boundary2--POuv..." delimiter line -- confirming this is a
    consistent trait of this partner's system, not a one-off of a single
    capture, and that mime_split.py's marker-concatenation approach
    (`b"--" + boundary`) needs to keep handling it."""
    raw = (SAMPLES_DIR / filename).read_bytes()
    match = re.search(
        rb'name="input-data".*?Content-Type:\s*multipart/encrypted;\s*boundary=(\S+?);',
        raw,
        re.DOTALL | re.IGNORECASE,
    )
    assert match is not None, f"{filename}: could not find input-data boundary"
    assert match.group(1).startswith(b"--")


@pytest.mark.parametrize("filename", SAMPLE_FILENAMES)
def test_real_sample_input_data_field_is_last_and_no_cte_header(filename):
    """Confirms two more consistent real-world traits: input-data is the
    last outer field (not where build_multipart_body() would place it), and
    the octet-stream part carries no content-transfer-encoding header at
    all -- both are tolerated today (parse_multipart_form() is
    order-agnostic; unwrap_pgp_encrypted() never reads CTE) but are worth
    locking in explicitly."""
    raw = (SAMPLES_DIR / filename).read_bytes()
    input_data_pos = raw.index(b'name="input-data"')
    refnum_orig_pos = raw.index(b'name="refnum-orig"')
    assert input_data_pos > refnum_orig_pos

    # The octet-stream part's content-type header is immediately followed
    # by a blank line (no content-transfer-encoding header in between).
    assert b"content-type: application/octet-stream\n\n" in raw
